/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTriageRouteImport } from './routes/_app.triage'
import { Route as AppHotspotsRouteImport } from './routes/_app.hotspots'
import { Route as AppExplorerRouteImport } from './routes/_app.explorer'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTriageRoute = AppTriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => AppRoute,
} as any)
const AppHotspotsRoute = AppHotspotsRouteImport.update({
  id: '/hotspots',
  path: '/hotspots',
  getParentRoute: () => AppRoute,
} as any)
const AppExplorerRoute = AppExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/analytics': typeof AppAnalyticsRoute
  '/explorer': typeof AppExplorerRoute
  '/hotspots': typeof AppHotspotsRoute
  '/triage': typeof AppTriageRoute
}
export interface FileRoutesByTo {
  '/analytics': typeof AppAnalyticsRoute
  '/explorer': typeof AppExplorerRoute
  '/hotspots': typeof AppHotspotsRoute
  '/triage': typeof AppTriageRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/explorer': typeof AppExplorerRoute
  '/_app/hotspots': typeof AppHotspotsRoute
  '/_app/triage': typeof AppTriageRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analytics' | '/explorer' | '/hotspots' | '/triage'
  fileRoutesByTo: FileRoutesByTo
  to: '/analytics' | '/explorer' | '/hotspots' | '/triage' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/analytics'
    | '/_app/explorer'
    | '/_app/hotspots'
    | '/_app/triage'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/triage': {
      id: '/_app/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof AppTriageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hotspots': {
      id: '/_app/hotspots'
      path: '/hotspots'
      fullPath: '/hotspots'
      preLoaderRoute: typeof AppHotspotsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explorer': {
      id: '/_app/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof AppExplorerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppExplorerRoute: typeof AppExplorerRoute
  AppHotspotsRoute: typeof AppHotspotsRoute
  AppTriageRoute: typeof AppTriageRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppExplorerRoute: AppExplorerRoute,
  AppHotspotsRoute: AppHotspotsRoute,
  AppTriageRoute: AppTriageRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
